export enum commissionrole{

    SUPER_ADMIN = "SUPERADMIN",
    ADMINISTRATION="ADMINISTRATION",
    SECURITE = "SECURITE",
    ACCUEIL = "ACCUEIL",
    COMMUNICATION = "COMMUNICATION",
    AUTRE = "AUTRE"    

}