export enum seminaristeSchoolEnum{
    CP1 = "CP1",
    CP2 = "CP2",
    CE1 = "CE1",
    CE2 = "CE2",
    CM1 = "CM1",
    CM2 = "CM2",
    SIXIEME = "SIXIEME",
    CINQUIEME = "CINQUIEME",
    QUATRIEME = "QUATRIEME",
    TROISIEME = "TROISIEME",
    SECOND = "SECOND",
    PREMIERE = "PREMIERE",
    TERMINAL = "TERMINAL",
    PREMIEREANNEE = "BAC+1",
    DEUXIEMEANNE = "BAC+2",
    TROISIEMEANNEE = "BAC+3",
    MASTER1 = "MASTER1",
    MASTER2 = "MASTER2",
     DOCTORAT= "DOCTORAT",
}