export enum semiSousCoEnum{
    AUTRE ="AUTRE",
    YOPOUGON1 = "YOPOUGON1",
    YOPOUGON2 = "YOPOUGON2",
    YOPOUGON3 = "YOPOUGON3",
    ABOBO1 = "ABOB1",
    ABOBO2 = "COLLEGE_RODIN",
    TREICHVILLE = "TREIVILLE",
    MARCORY = "MARCORY",
    COCODY1 = "COCODY1",
    COCODY2 = "COCODY2",
    SONGON = "SONGON",
    ATTECOUBE = "ATTECOUBE",
    PLATEAU = "PLATEAU",
    BINGERVILLE = "BINGERVILLE",
    
}